### ISSUE TITLE
2주차 이슈 : 다중 프레임 구조, 단일 프레임 구조라는 것을 모르겠습니다.

### ISSUE THREAD

**Issue by euncheol-kim** [did-study/tobys_spring#1]
토비의 스프링 61페이지의
`  "DB를 오라클에서 MySQL로 바꾸면서, 웹 화면의 레이아웃을 다중 프레임 구조에서 단일 프레임에 Ajax를 적용한 구조로 바꾸고... ` 라는 구문이 나오는데 여기서 나오는 `다중 프레임 구조`와 `단일 프레임 구조`라는게 정확히 무엇인지 모르겠습니다.

**Comment by comeevery-git** [comment]
제가 이해하기로는 웹 화면의 레이아웃이 여러 화면 분할을 사용한다는 느낌으로 다중 프레임 구조, 하나의 화면 분할을 사용한다는 느낌으로 단일 프레임만 사용한다고 이야기한 것 같습니다.
해당 문단의 포인트는 DB 변경과 동시에 레이아웃 변경과 동시에 매출정보 전송 로직변경과 동시에 날짜 포맷 변경을 해주세요. 라고 요구사항이 한번에 올라오지 않는다는 것 같습니다.
"모든 변경과 발전은 한 번에 한 가지 관심사항에 집중해서 일어난다." 에 집중하시면 될 것 같습니다! :D

**Comment by comeevery-git** [comment]
> 토비의 스프링 61페이지의 ` "DB를 오라클에서 MySQL로 바꾸면서, 웹 화면의 레이아웃을 다중 프레임 구조에서 단일 프레임에 Ajax를 적용한 구조로 바꾸고...` 라는 구문이 나오는데 여기서 나오는 `다중 프레임 구조`와 `단일 프레임 구조`라는게 정확히 무엇인지 모르겠습니다.

제가 이해하기로는 웹 화면의 레이아웃이 여러 화면 분할을 사용한다는 느낌으로 다중 프레임 구조, 하나의 화면 분할을 사용한다는 느낌으로 단일 프레임만 사용한다고 이야기한 것 같습니다.
해당 문단의 포인트는 DB 변경과 동시에 레이아웃 변경과 동시에 매출정보 전송 로직변경과 동시에 날짜 포맷 변경을 해주세요. 라고 요구사항이 한번에 올라오지 않는다는 것 같습니다.
"모든 변경과 발전은 한 번에 한 가지 관심사항에 집중해서 일어난다." 에 집중하시면 될 것 같습니다! :D

**Comment by euncheol-kim** [comment]
쉽게 설명해주셔서 한 번에 이해했습니다. 감사합니다!
